// import tovar1 from "../images/1.png";
import {
  brand1,
  brand2,
  brand3,
  brand4,
  brand5,
  brand6,
  brand7,
  brand8,
  brand9,
} from "../images";
export const products = [
  {
    type: "simple",
    id: 1,
    sku: "s1",
    title: "Product 1",
    regular_price: {
      currency: "USD",
      value: 27.12,
    },
    image: brand1,
    brand: 9,
    count: 0,
  },
  {
    type: "simple",
    id: 2,
    sku: "s2",
    title: "Product 2",
    regular_price: {
      currency: "USD",
      value: 36.87,
    },
    image: brand2,
    brand: 8,
    count: 0,
  },
  {
    type: "simple",
    id: 3,
    sku: "s3",
    title: "Product 3",
    regular_price: {
      currency: "USD",
      value: 28.91,
    },
    image: brand3,
    brand: 2,
    count: 0,
  },
  {
    type: "simple",
    id: 4,
    sku: "s4",
    title: "Product 4",
    regular_price: {
      currency: "USD",
      value: 41.23,
    },
    image: brand4,
    brand: 7,
    count: 0,
  },
  {
    type: "simple",
    id: 5,
    sku: "s5",
    title: "Product 5",
    regular_price: {
      currency: "USD",
      value: 88.0,
    },
    image: brand5,
    brand: 3,
    count: 0,
  },
  {
    type: "simple",
    id: 6,
    sku: "s6",
    title: "Product 6",
    regular_price: {
      currency: "USD",
      value: 127.41,
    },
    image: brand6,
    brand: 6,
    count: 0,
  },
  {
    type: "simple",
    id: 7,
    sku: "s7",
    title: "Product 7",
    regular_price: {
      currency: "USD",
      value: 123.4,
    },
    image: brand7,
    brand: 5,
    count: 0,
  },
  {
    type: "simple",
    id: 8,
    sku: "s8",
    title: "Product 8",
    regular_price: {
      currency: "USD",
      value: 92.32,
    },
    image: brand8,
    brand: 1,
    count: 0,
  },
  {
    type: "simple",
    id: 9,
    sku: "s9",
    title: "Product 9",
    regular_price: {
      currency: "USD",
      value: 53.4,
    },
    image: brand9,
    brand: 2,
    count: 0,
  },
];
